lst = [1,2,3,4,5,6]
print(type(lst))
print(lst)
print('--------------')
lst.insert(7,7)
print(lst)
print('--------------')
lst.extend([8,9,10])
print(lst)
print('--------------')
print(lst.pop())
print(lst)
print('--------------')
lst.pop(6)
print(lst)
print('--------------')
lst = [1,1,6,3,1,5,2,4]
print(lst)
print(lst.count(1))
print(len(lst))
print("-------------")
print(lst.index(3,0,4))
lst.sort()
print(lst)
print('--------------')
lst.remove(6)
print(lst)
print('--------------')
print("Min Val: ", min(lst))
print("Max Val: " , max(lst))
print("Avg Val: ", sum(lst)/len(lst))
print("--------------")
lst1 = lst.copy()
lst.clear()
print(lst1)



