import numpy as np

mylist = np.arange(0,5)
mylist2= np.arange(5,10)
arr = np.array([mylist,mylist2])
print(arr)
print('----------------')
print(arr.shape)
print(arr.dtype)
print(arr.reshape(5,2))
print(arr.reshape(1,10))
print(arr.reshape(10,1))
print('--------------------')
combinations = np.prod(arr.shape)
print(combinations)  # 6
print('--------------------')
print(arr)
print('--------------------')
print(arr[0:,1:])
print('--------------------')
print(arr[:1,2:])
print('--------------------')
print(arr[1:,2:])
print('--------------------')
print(arr[1:,1:])
